coverage:
  status:
    project:
      default:
        target: auto

flags:
  unit:
    paths:
      - ".*"
    carryforward: true

comment:
  show_carryforward_flags: true

codecov:
  disable_default_path_fixes: true
